apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cert-manager.yaml
  - aws-load-balancer-controller.yaml
  - external-secrets.yaml
  - argo-rollouts.yaml
  - kube-prometheus-stack.yaml
  - aws-for-fluent-bit.yaml
  - loki.yaml
  - listmonk.yaml
