apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: listmonk
resources:
  - externalsecret.yaml
  - configmap.yaml
  - rollout.yaml
  - service-active.yaml
  - service-preview.yaml
  - ingress.yaml

images:
  - name: ghcr.io/jluisreyvargas/listmonk2
    newName: ghcr.io/jluisreyvargas/listmonk2
    newTag: REPLACE_ME_TAG
